### ISSUE TITLE
Crash when no settings file existed yet

### ISSUE THREAD

**Issue by Apanatshka** [Luke-Nukem/rs_life#2]
When `$HOME/.config/rs_life/` exists, but no settings file, `config.toml` is created in the directory but not filled with any contents. Thereafter the program crashes on trying to read a valid config:

```
thread 'main' panicked at 'Error reading config: Error { repr: Os { code: 9, message: "Bad file descriptor" } }', ../src/libcore/result.rs:799
```

**Comment by Luke-Nukem** [comment]
Fixed by commit 6bfb842247a614c334ec5ac1bce808c7212999eb
